version: '3.9'

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true